exclude: 'app/assets/stylesheets/rails_admin/**'

linters:
  Comment:
    exclude: 'app/assets/stylesheets/application.scss'
  EmptyLineBetweenBlocks:
    enabled: false
  NestingDepth:
    max_depth: 5
  PropertySpelling:
    extra_properties:
     - text-size-adjust
  SelectorDepth:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: false
  QualifyingElement:
    enabled: false
  VendorPrefixes:
    enabled: false
