
baseUrl: https://calcentral-dev.berkeley.edu
#baseUrl: https://calcentral-qa.berkeley.edu

calNetUrl: https://auth-test.berkeley.edu

webDriver: firefox
# web_driver: chrome
# web_driver: safari
# web_driver: ie

pageEventTimeout: 1
pageLoadTimeout: 3
finResourcesLinksTimeout: 20
financialsTimeout: 5
